(function(){function V(a){w||F();var b=a.target;if(a.defaultPrevented||a.ctrlKey||x(l,"embed")||x(b,"embed")&&/\.pdf/i.test(b.src)||x(l,"object")||b.shadowRoot)return!0;var d=-a.wheelDeltaX||a.deltaX||0,c=-a.wheelDeltaY||a.deltaY||0;W&&(a.wheelDeltaX&&u(a.wheelDeltaX,120)&&(d=a.wheelDeltaX/Math.abs(a.wheelDeltaX)*-120),a.wheelDeltaY&&u(a.wheelDeltaY,120)&&(c=a.wheelDeltaY/Math.abs(a.wheelDeltaY)*-120));d||c||(c=-a.wheelDelta||0);1===a.deltaMode&&(d*=40,c*=40);b=G(b);if(!b||X(c))return!0;1.2<Math.abs(d)&&
(d*=e.stepSize/120);1.2<Math.abs(c)&&(c*=e.stepSize/120);H(b,d,c);a.preventDefault();I()}function Y(a){document.body.contains(l)||(l=document.activeElement);var b,d=0;b=0;var c=G(l);if(!c)return!0;var g=c.clientHeight;c==document.body&&(g=window.innerHeight);switch(a.keyCode){case h.up:b=-e.arrowScroll;break;case h.down:b=e.arrowScroll;break;case h.spacebar:b=a.shiftKey?1:-1;b=-b*g*.9;break;case h.pageup:b=.9*-g;break;case h.pagedown:b=.9*g;break;case h.home:c==document.body&&document.scrollingElement&&
(c=document.scrollingElement);b=-c.scrollTop;break;case h.end:g=c.scrollHeight-c.scrollTop-g;b=0<g?g+10:0;break;case h.left:d=-e.arrowScroll;break;case h.right:d=e.arrowScroll;break;default:return!0}H(c,d,b);a.preventDefault();I()}function X(a){if(a){k.length||(k=[a,a,a]);a=Math.abs(a);k.push(a);k.shift();clearTimeout(J);J=setTimeout(function(){try{localStorage.SS_deltaBuffer=k.join(",")}catch(d){}},1E3);var b=120<a&&y(a),b=!y(120)&&!y(100)&&!b;return 50>a?!0:b}}var e={frameRate:800,animationTime:800,
stepSize:50,pulseAlgorithm:!0,pulseScale:4,pulseNormalize:1,accelerationDelta:50,accelerationMax:3,keyboardSupport:!0,arrowScroll:50,fixedBackground:!0,excluded:""},K=0,L=0,w=!1,m=document.documentElement,l,M,k=[],J,W=/^Mac/.test(navigator.platform),h={left:37,up:38,right:39,down:40,spacebar:32,pageup:33,pagedown:34,end:35,home:36},F=function(){if(!w&&document.body){w=!0;var a=document.body,b=document.documentElement,d=window.innerHeight,c=a.scrollHeight;m=0<=document.compatMode.indexOf("CSS")?b:
a;l=a;e.keyboardSupport&&window.addEventListener("keydown",Y,!1);if(Z&&c>d&&(a.offsetHeight<=d||b.offsetHeight<=d)){var g=document.createElement("div");g.style.cssText="position:absolute; z-index:-10000; top:0; left:0; right:0; height:"+m.scrollHeight+"px";document.body.appendChild(g);var f,c=function(){f||(f=setTimeout(function(){g.style.height="0";g.style.height=m.scrollHeight+"px";f=null},500))};setTimeout(c,10);window.addEventListener("resize",c,!1);M=new aa(c);M.observe(a,{attributes:!0,childList:!0,
characterData:!1});m.offsetHeight<=d&&(d=document.createElement("div"),d.style.clear="both",a.appendChild(d))}e.fixedBackground||(a.style.backgroundAttachment="scroll",b.style.backgroundAttachment="scroll")}},r=[],z=!1,A=Date.now(),H=function(a,b,d){ba(b,d);if(1!=e.accelerationMax){var c=Date.now()-A;c<e.accelerationDelta&&(c=(1+50/c)/2,1<c&&(c=Math.min(c,e.accelerationMax),b*=c,d*=c));A=Date.now()}r.push({x:b,y:d,lastX:0>b?.99:-.99,lastY:0>d?.99:-.99,start:Date.now()});if(!z){var c=N(),g=a===c||
a===document.body;null==a.$scrollBehavior&&ca(a)&&(a.$scrollBehavior=a.style.scrollBehavior,a.style.scrollBehavior="auto");var f=function(){for(var c=Date.now(),h=0,k=0,l=0;l<r.length;l++){var n=r[l],p=c-n.start,m=p>=e.animationTime,q=m?1:p/e.animationTime;e.pulseAlgorithm&&(p=q,1<=p?q=1:0>=p?q=0:(1==e.pulseNormalize&&(e.pulseNormalize/=O(1)),q=O(p)));p=n.x*q-n.lastX>>0;q=n.y*q-n.lastY>>0;h+=p;k+=q;n.lastX+=p;n.lastY+=q;m&&(r.splice(l,1),l--)}g?window.scrollBy(h,k):(h&&(a.scrollLeft+=h),k&&(a.scrollTop+=
k));b||d||(r=[]);r.length?P(f,a,1E3/e.frameRate+1):(z=!1,null!=a.$scrollBehavior&&(a.style.scrollBehavior=a.$scrollBehavior,a.$scrollBehavior=null))};P(f,a,0);z=!0}},da=function(a){return l=a.target},B=function(){var a=0;return function(b){return b.uniqueID||(b.uniqueID=a++)}}(),Q={},C={},R,v={},I=function(){clearTimeout(R);R=setInterval(function(){return Q=C=v={}},1E3)},D=function(a,b,d){d=d?Q:C;for(var c=a.length;c--;)d[B(a[c])]=b;return b},G=function(a){var b=[],d=document.body,c=m.scrollHeight;
do{var e=C[B(a)];if(e)return D(b,e);b.push(a);if(c===a.scrollHeight){if(S(m)&&S(d)||T(m))return D(b,N())}else if(a.clientHeight+10<a.scrollHeight&&T(a))return D(b,a)}while(a=a.parentElement)},S=function(a){return"hidden"!==getComputedStyle(a,"").getPropertyValue("overflow-y")},T=function(a){a=getComputedStyle(a,"").getPropertyValue("overflow-y");return"scroll"===a||"auto"===a},ca=function(a){var b=B(a);null==v[b]&&(a=getComputedStyle(a,"")["scroll-behavior"],v[b]="smooth"==a);return v[b]},x=function(a,
b){return a&&(a.nodeName||"").toLowerCase()===b.toLowerCase()},ba=function(a,b){a=0<a?1:-1;b=0<b?1:-1;if(K!==a||L!==b)K=a,L=b,r=[],A=0};if(window.localStorage&&localStorage.SS_deltaBuffer)try{k=localStorage.SS_deltaBuffer.split(",")}catch(a){}var u=function(a,b){return Math.floor(a/b)==a/b},y=function(a){return u(k[0],a)&&u(k[1],a)&&u(k[2],a)},P=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||function(a,b,d){window.setTimeout(a,
d||1E3/60)}}(),aa=window.MutationObserver||window.WebKitMutationObserver||window.MozMutationObserver,N=function(){var a=document.scrollingElement;return function(){if(!a){var b=document.createElement("div");b.style.cssText="height:10000px;width:1px;";document.body.appendChild(b);var d=document.body.scrollTop;window.scrollBy(0,3);a=document.body.scrollTop!=d?document.body:document.documentElement;window.scrollBy(0,-3);document.body.removeChild(b)}return a}}(),O=function(a){var b;a*=e.pulseScale;1>
a?b=a-(1-Math.exp(-a)):(b=Math.exp(-1),a=1-Math.exp(-(a-1)),b+=a*(1-b));return b*e.pulseNormalize},f=window.navigator.userAgent,t=/Edge/.test(f),E=/chrome/i.test(f)&&!t,t=/safari/i.test(f)&&!t,ea=/mobile/i.test(f),fa=/Windows NT 6.1/i.test(f)&&/rv:11/i.test(f),Z=t&&(/Version\/8/i.test(f)||/Version\/9/i.test(f)),f=(E||t||fa)&&!ea,U=!1;try{window.addEventListener("test",null,Object.defineProperty({},"passive",{get:function(){U=!0}}))}catch(a){}E=U?{passive:!1}:!1;if(t="onwheel"in document.createElement("div")?
"wheel":"mousewheel",f)window.addEventListener(t,V,E||!1),window.addEventListener("mousedown",da,!1),window.addEventListener("load",F,!1)})();
